provider:
  name: netboxbgp
resources:
  session:
    create:
      path: /api/plugins/bgp/bgpsession/
      method: POST
    read:
      path: /api/plugins/bgp/bgpsession/{id}/
      method: GET
    update:
      path: /api/plugins/bgp/bgpsession/{id}/
      method: PUT
    delete:
      path: /api/plugins/bgp/bgpsession/{id}/
      method: DELETE
    schema:
      ignores:
        - custom_fields
        - export_policies.custom_fields
        - import_policies.custom_fields
  peergroup:
    create:
      path: /api/plugins/bgp/peer-group/
      method: POST
    read:
      path: /api/plugins/bgp/peer-group/{id}/
      method: GET
    update:
      path: /api/plugins/bgp/peer-group/{id}/
      method: PUT
    delete:
      path: /api/plugins/bgp/peer-group/{id}/
      method: DELETE
    schema:
      ignores:
        - custom_fields
        - export_policies.custom_fields
        - import_policies.custom_fields
  prefixlist:
    create:
      path: /api/plugins/bgp/prefix-list/
      method: POST
    read:
      path: /api/plugins/bgp/prefix-list/{id}/
      method: GET
    update:
      path: /api/plugins/bgp/prefix-list/{id}/
      method: PUT
    delete:
      path: /api/plugins/bgp/prefix-list/{id}/
      method: DELETE
    schema:
      ignores:
        - custom_fields
  prefixlistrule:
    create:
      path: /api/plugins/bgp/prefix-list-rule/
      method: POST
    read:
      path: /api/plugins/bgp/prefix-list-rule/{id}/
      method: GET
    update:
      path: /api/plugins/bgp/prefix-list-rule/{id}/
      method: PUT
    delete:
      path: /api/plugins/bgp/prefix-list-rule/{id}/
      method: DELETE
    schema:
      ignores:
        - custom_fields
