provider:
  name: netboxbgp
resources:
  session:
    create:
      path: /api/plugins/bgp/session/
      method: POST
    read:
      path: /api/plugins/bgp/session/{id}/
      method: GET
    update:
      path: /api/plugins/bgp/session/{id}/
      method: PUT
    delete:
      path: /api/plugins/bgp/session/{id}/
      method: DELETE
    schema:
      ignores:
        - custom_fields
        - export_policies.custom_fields
        - import_policies.custom_fields
      attributes:
        overrides:
          status:
            description: "`offline`, `active`, `planned` or `failed`"
  peer_group:
    create:
      path: /api/plugins/bgp/peer-group/
      method: POST
    read:
      path: /api/plugins/bgp/peer-group/{id}/
      method: GET
    update:
      path: /api/plugins/bgp/peer-group/{id}/
      method: PUT
    delete:
      path: /api/plugins/bgp/peer-group/{id}/
      method: DELETE
    schema:
      ignores:
        - custom_fields
        - export_policies.custom_fields
        - import_policies.custom_fields
  prefix_list:
    create:
      path: /api/plugins/bgp/prefix-list/
      method: POST
    read:
      path: /api/plugins/bgp/prefix-list/{id}/
      method: GET
    update:
      path: /api/plugins/bgp/prefix-list/{id}/
      method: PUT
    delete:
      path: /api/plugins/bgp/prefix-list/{id}/
      method: DELETE
    schema:
      ignores:
        - custom_fields
      attributes:
        overrides:
          family:
            description: "`ipv4` or `ipv6`"
  prefix_list_rule:
    create:
      path: /api/plugins/bgp/prefix-list-rule/
      method: POST
    read:
      path: /api/plugins/bgp/prefix-list-rule/{id}/
      method: GET
    update:
      path: /api/plugins/bgp/prefix-list-rule/{id}/
      method: PUT
    delete:
      path: /api/plugins/bgp/prefix-list-rule/{id}/
      method: DELETE
    schema:
      ignores:
        - custom_fields
      attributes:
        overrides:
          action:
            description: "`permit` or `deny`"
  aspath_list:
    create:
      path: /api/plugins/bgp/aspath-list/
      method: POST
    read:
      path: /api/plugins/bgp/aspath-list/{id}/
      method: GET
    update:
      path: /api/plugins/bgp/aspath-list/{id}/
      method: PUT
    delete:
      path: /api/plugins/bgp/aspath-list/{id}/
      method: DELETE
    schema:
      ignores:
        - custom_fields
  aspath_list_rule:
    create:
      path: /api/plugins/bgp/aspath-list-rule/
      method: POST
    read:
      path: /api/plugins/bgp/aspath-list-rule/{id}/
      method: GET
    update:
      path: /api/plugins/bgp/aspath-list-rule/{id}/
      method: PUT
    delete:
      path: /api/plugins/bgp/aspath-list-rule/{id}/
      method: DELETE
    schema:
      ignores:
        - custom_fields
      attributes:
        overrides:
          action:
            description: "`permit` or `deny`"
  routing_policy:
    create:
      path: /api/plugins/bgp/routing-policy/
      method: POST
    read:
      path: /api/plugins/bgp/routing-policy/{id}/
      method: GET
    update:
      path: /api/plugins/bgp/routing-policy/{id}/
      method: PUT
    delete:
      path: /api/plugins/bgp/routing-policy/{id}/
      method: DELETE
    schema:
      ignores:
        - custom_fields
  routing_policy_rule:
    create:
      path: /api/plugins/bgp/routing-policy-rule/
      method: POST
    read:
      path: /api/plugins/bgp/routing-policy-rule/{id}/
      method: GET
    update:
      path: /api/plugins/bgp/routing-policy-rule/{id}/
      method: PUT
    delete:
      path: /api/plugins/bgp/routing-policy-rule/{id}/
      method: DELETE
    schema:
      ignores:
        - custom_fields
        - match_aspath_list.custom_fields
        - match_community.custom_fields
        - match_community_list.custom_fields
        - match_ip_address.custom_fields
        - match_ipv6_address.custom_fields
      attributes:
        overrides:
          action:
            description: "`permit` or `deny`"
          match_custom:
            description: Provide a JSON-serialized object.
          set_actions:
            description: Provide a JSON-serialized object.

data_sources:
  prefix_list:
    read:
      path: /api/plugins/bgp/prefix-list/{id}/
      method: GET
    schema:
      ignores:
        - custom_fields
        - export_policies.custom_fields
        - import_policies.custom_fields
